version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:15
    depends_on:
      - postgresql
    ports:
      - "9080:8080"
    volumes:
      - "./theme_podkrepi:/opt/bitnami/keycloak/themes/theme_podkrepi"

volumes:
  postgresql_data:
    driver: local
